# -*- coding: utf-8 -*-
"""Segund_Entregable_CDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IpmlBXcqsL3dJammAqyDrG4r9HJCW7iP

# Ciencia de datos aplicada (ITBA): Segundo entregable

**Equipo:** Ian Bernasconi, Jeremias Feferovich

**Nombre del proyecto**: Batata Real State

Los datos fueron obtenidos haciendo scrapping de https://properati.com.ar/.

Inicialmente quisimos obtenerlos de https://www.zonaprop.com.ar/, pero tuvimos complicaciones por cómo maneja zonaprop la paginación, lo que hizo que tuviéramos muchos datos repetidos.

Al realizar el scrapper para properati, iterando con el url base https://www.properati.com.ar/s/capital-federal/venta, vemos que 69.269 propiedades.
Filtrando por tipo de propiedad Casa o Departamento, para excluir otros tipos como Locales o Cocheras, nos quedan 49959.

Sin embargo, al correr el scrapper, nos encontramos con que a partir de la página 168 ya no obteníamos resultados. Con 30 propiedades por página, esto nos limitaba a alrededor de 5000 propiedades. Para solucionar esto, scrappeamos por separado para cada barrio de la ciudad, dividiendo Palermo en Palermo Chico, Palermo Viejo, Palermo Hollywood y Palermo Soho, ya que se pasaba del límite de 5000 propiedades.

Como comentario adicional, para realizar el scrapper se utilizó el MCP de Playwright para facilitar el reconocimiento de la estructura de las páginas a scrappear.

El código del scrapper puede verse en https://github.com/JeremiasFeferovich/CDA-TP

### 🧾 1. Importación y carga de librerías
"""

!pip install category_encoders

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import category_encoders as ce
import io
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from google.colab import files

# Configuraciones de estilo
sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10, 6)

"""### 🧾 2. Carga de datos"""

file_id = "15nLVZdk6KSnKo4TmzjFHlBs6rmkPeFDJ"
url = f'https://drive.google.com/uc?id={file_id}'
df = pd.read_csv(url)
print(df.shape)
print(df.head())

"""#### 🗒️ 2.1 Descripción del dataset
Este dataset contiene 46 variables sobre propiedades en venta en la Ciudad de Buenos Aires, obtenidas mediante técnicas de web scraping en portales inmobiliarios. Incluye información estructural de las viviendas, características adicionales y datos de localización.

Tamaño del dataset: 49959 registros.

- Variables numéricas

  - price: precio de publicación de la propiedad .

  - surface_total: superficie total en metros cuadrados.

  - surface_covered: superficie cubierta .

  - bathrooms: cantidad de baños.

  - bedrooms: cantidad de dormitorios.

  - rooms: número total de ambientes .

  - area: área de la propiedad.

  - balcony_count: cantidad de balcones.

  - photo_count: cantidad de fotos de la publicación.

  - page_number: número de página en el scraping.

  - parking_spaces: cantidad de cocheras.

  - expenses: valor mensual de expensas.

  - total_floors / floor_number: pisos totales y número de piso.

- Variables categóricas

  - currency: tipo de moneda (USD, ARS, etc.).

  - neighborhood / neighborhood_slug / scraped_neighborhood: barrio de la Ciudad de Buenos Aires.

  - location / coordinates / latitude / longitude: información geográfica.

  - full_address: dirección completa de la propiedad.

  - property_type: tipo de propiedad (departamento, casa, PH, etc.).

  - property_status: estado de la propiedad.

  - orientation: orientación del inmueble.

  - labels: etiquetas descriptivas de la publicación.

  - title: título del aviso.

  - description: texto descriptivo.

  - detail_url: enlace a la publicación.

  - published_date: fecha de publicación.

  - publisher: entidad que publica .

  - amenities: listado de amenidades asociadas (ej. “pileta, parrilla, seguridad”).

- Variables booleanas (amenities específicas)

  - has_balcony, has_doorman, has_garage, has_grill, has_gym, has_pool, has_security, has_storage, has_sum, has_terrace: indican presencia de determinadas características.

- Variables identificadoras

  - property_id: identificador único de la propiedad.

  - agency_name: nombre de la inmobiliaria.

- Metadatos del scraping

  - page_number, scraping_date: información técnica del proceso de scraping.

- Variable objetivo

  - price: precio de publicación (expresado mayormente en USD)

### 🔍 3. Análisis exploratorio de datos (EDA)

####🚀 Primer acercamiento al dataset
"""

# Información general
df.info()

""" Gran parte de las variables aparecen cargadas con tipo object. Esto implica la necesidad de realizar un proceso de conversión de tipos para poder analizarlas.


"""

# Información general
df.describe()

# Valores faltantes
df.isnull().sum()

"""Borrar tuplas que tengan NaN en "price" que es el valor objetivo

"""

df = df.dropna(subset=["price"])

"""Hacemos un chequeo de propiedades repetidas segun property_id:"""

# Vemos el estado inicial
print("Shape inicial:", df.shape)

# Elimina duplicados manteniendo la primera aparición
df = df.drop_duplicates(subset="property_id", keep="first")

# Luego de eliminar tuplas duplicadas
print("Shape final:", df.shape)

"""Por ende, no hay duplicados en el dataset

####🔢 Distribucion de Variables numericas
"""

# Distribuciones de variables numéricas
cols = ["price", "surface_total", "bathrooms", "bedrooms", "area", "balcony_count"]
df_numeric = df[cols]

df_numeric.hist(bins=10, figsize=(15, 10), layout=(4, 2))
plt.suptitle('Distribución de variables numéricas')
plt.tight_layout()
plt.show()

"""#### 🧊 Detección de outliers con boxplots


"""

fig, axes = plt.subplots(3, 2, figsize=(15, 10))

columnas = df_numeric.columns

for i, ax in enumerate(axes.flat):
    sns.boxplot(y=df[columnas[i]], ax=ax)
    ax.set_title(columnas[i])

plt.suptitle('Boxplots de variables numéricas', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""#### 🔗 Matriz de correlación entre variables numéricas"""

plt.figure(figsize=(12, 8))
sns.heatmap(df_numeric.corr(), annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Matriz de correlación")
plt.show()

"""#### 📊 Relación entre variables: ejemplo surface vs price"""

plt.figure(figsize=(10, 6))
plt.scatter(df["surface_total"], df["price"], alpha=0.3, edgecolor="k", s=20)
plt.title("Distribución del precio según la superficie")
plt.xlabel("Superficie (m²)")
plt.ylabel("Precio")

# Mejorar eje X
# plt.xscale("log")                # alternativa si preferís log
plt.xticks(rotation=45)
plt.locator_params(axis="x", nbins=10)

plt.show()

"""### 🧼 4. Diagnóstico de calidad de datos
- Valores faltantes
  - Se observa una gran cantidad de columnas con valores nulos totales o casi totales, lo que impacta negativamente en la completitud del dataset.
  - Columnas completamente vacías (sin valor alguno): description, expenses, floor_number, orientation, parking_spaces, property_status, surface_covered, total_floors.
  - Columnas con nulos parciales relevantes:
    - area: 14.560 nulos (~29%).
    - bathrooms: 2.138 nulos (~4%).
    - bedrooms: 7.823 nulos (~16%).
    - currency: 504 nulos (~1%).
    - rooms: 49.893 nulos (~99%).
    - surface_total: 14.560 nulos (~29%).
- Outliers
  - La variable price presenta un valor máximo de 3995 millones USD.
  - La desviación estándar (~ 17.9 millones) es desproporcionada frente al promedio (~323 mil).
  - En bathrooms y bedrooms, los máximos (280 y 51 respectivamente) son inverosímiles para propiedades residenciales y sugieren errores.
  - area / surface_total presentan valores máximos de 970 m², que podrían ser válidos para propiedades de alta gama, pero conviene verificar su distribución.
- Variables que deben ser eliminadas
  - rooms tiene solo 66 valores no nulos y una desviación estándar igual a 0, lo que indica falta total de variabilidad. Por lo tanto, no aporta información útil.
  - expenses, orientation, floor_number, parging_spaces, property_status, surface_covered y total_floors están completamente vacías.
  - Las columnas agency_name, description, detail_url, photo_count,  published_date, publisher, title no otorgan información relevante
  - Metadatos del scrapping: page_number, property_id (nos sirvió para borrar duplicados), scraping_date
  - Las columnas full_address, location, neighborhood, neighborhood_slug, scraped_neighborhood otorgan las misma inforamación. Nos quedaremos con location y borraremos las demás.
  - Las columnas area y surface_total son idénticas por lo que nos quedaremos solo con area.
  - Los valores posibles de la columna amenities son considerados como booleanos en nuevas columnas

### 🧪 5. Transformaciones realizadas

#### Limpieza de columnas
"""

cols_to_drop = [
    'amenities', 'rooms', 'expenses', 'orientation', 'floor_number', 'parking_spaces',
    'property_status', 'surface_covered', 'total_floors',
    'agency_name', 'description', 'detail_url', 'photo_count',
    'published_date', 'publisher', 'title',
    'page_number', 'property_id', 'scraping_date',
    'full_address', 'neighborhood', 'neighborhood_slug', 'scraped_neighborhood' # nos quedamos con location
    'surface_total'  # nos quedamos con 'area'
]

df.drop(columns=[c for c in cols_to_drop if c in df.columns], inplace=True, errors='ignore')

print(f" Total actual de columnas: {df.shape[1]} columnas")

"""#### Valores faltantes"""

cols_imputar = ['currency']

# Mostrar cantidad de nulos antes
print("🔍 Nulos antes de imputar:")
for col in cols_imputar:
    print(f" - {col}: {df[col].isna().sum()} nulos")

df['currency'] = df['currency'].fillna('USD')  # default más común

print("\nNulos después de imputar:")
for col in cols_imputar:
    print(f" - {col}: {df[col].isna().sum()} nulos restantes")

cols_eliminar_si_nulos = ['area', 'bathrooms', 'bedrooms', 'currency']

# Mostrar cantidad de nulos antes
print("🔍 Nulos antes de eliminar:")
for col in cols_eliminar_si_nulos:
    print(f" - {col}: {df[col].isna().sum()} nulos")

# Eliminar filas que tengan nulos en cualquiera de esas columnas
before_drop = df.shape[0]
df = df.dropna(subset=cols_eliminar_si_nulos)
after_drop = df.shape[0]

print(f"\n🧹 Filas eliminadas: {before_drop - after_drop}")
print(f"✅ Total de filas restantes: {after_drop}")

# Verificación final
print("\n🔍 Nulos después de eliminar:")
for col in cols_eliminar_si_nulos:
    print(f" - {col}: {df[col].isna().sum()} nulos restantes")

print(f"\nCantidad total de tuplas en el DataFrame: {len(df)}")

# Eliminación de filas con valores 0 en columnas clave

cols_sin_ceros = ['area', 'bathrooms', 'bedrooms', 'price']

print("🔍 Cantidad de valores 0 antes de eliminar:")
for col in cols_sin_ceros:
    print(f" - {col}: {(df[col] == 0).sum()} filas con 0")

# Eliminar filas que tengan 0 en cualquiera de esas columnas
before_drop = df.shape[0]
df = df[~(df[cols_sin_ceros] == 0).any(axis=1)]
after_drop = df.shape[0]

print(f"\nFilas eliminadas por contener valores 0 en columnas clave: {before_drop - after_drop}")
print(f"Total de filas restantes: {after_drop}")

# Verificación
print("\nCantidad de valores 0 después de eliminar:")
for col in cols_sin_ceros:
    print(f" - {col}: {(df[col] == 0).sum()} filas con 0")

"""#### Trato de Outliers"""

numeric_cols = ['price', 'area', 'bathrooms', 'bedrooms', 'balcony_count']

print("Antes del tratamiento de outliers:\n")
for col in numeric_cols:
    print(f"→ {col}")
    print(f"   Media: {df[col].mean():,.2f}")
    print(f"   Desviación estándar: {df[col].std():,.2f}")
    print(f"   Mínimo: {df[col].min():,.2f}")
    print(f"   Máximo: {df[col].max():,.2f}\n")

"""Se aplica un tratamiento diferenciado de outliers para mantener la coherencia de los datos sin eliminar información útil.
- En price:
  - Se filtran precios mínimos sin sentido: eliminar valores extremadamente bajos, precios menores a 10 000 USD.

  - Analizar los precios más altos y compararlos con los percentiles estadísticos para decidir si son razonables o deben recortarse.


"""

min_valid_price = 10000  # umbral mínimo razonable en USD
before_min_filter = len(df)
df = df[df['price'] >= min_valid_price]
after_min_filter = len(df)

print(f" Filtro inferior aplicado a 'price' (< {min_valid_price:,} USD)")
print(f" Filas eliminadas: {before_min_filter - after_min_filter}")
print(f" Total de filas restantes: {after_min_filter}")

# --- 2️⃣ Chequeo de valores máximos (outliers altos) ---
q1 = df['price'].quantile(0.25)
q3 = df['price'].quantile(0.75)
iqr = q3 - q1
upper_limit = q3 + 1.5 * iqr

print("\n📊 Análisis de valores altos:")
print(f" - Q3 (percentil 75): {q3:,.2f}")
print(f" - Límite superior (Q3 + 1.5*IQR): {upper_limit:,.2f}")
print(f" - Máximo actual: {df['price'].max():,.2f}")

"""Revisando según precio máximo:"""

# Revisión de las propiedades más caras
top_prices = df.nlargest(10, 'price')[['price', 'area', 'bedrooms', 'bathrooms', 'location', 'currency']]
print("\n Propiedades con los precios más altos:\n")
print(top_prices)

"""Vamos a suponer que los cuatro primeros valores son errores en el scarapping o de carga de las propiedades. Eliminaremos todo lo que esté por encima de 12 millones USD."""

max_valid_price = 12000000
before = len(df)
df = df[df['price'] <= max_valid_price]
after = len(df)

print(f"Se eliminaron {before - after} propiedades con precio > {max_valid_price:,} USD")
print(f"\nNuevo máximo de price: {df['price'].max():,.2f} USD")

"""- En area, se eliminan superficies irreales (menores a 30 m²)."""

menos_20 = (df['area'] < 30).sum()

print(f" Propiedades con área menor a 30 m²: {menos_20}")

total = len(df)
porcentaje = (menos_20 / total) * 100
print(f" Propiedades con área < 30 m²: {menos_20} ({porcentaje:.2f}% del total)")

# Recorte para área (filtrado por límites razonables: menos de 2% total)
min_area = 30
df = df[(df['area'] >= min_area)]
print(f" Recorte aplicado a 'area' | Rango final: {df['area'].min():,.2f} - {df['area'].max():,.2f}")

# Mostrar las 30 propiedades con mayor área
top_areas = df.nlargest(30, 'area')[['area', 'price', 'bedrooms', 'bathrooms']]
print("🏠 Top 30 propiedades con mayor área:\n")
print(top_areas)

# Calcular estadísticas generales
q1 = df['area'].quantile(0.25)
q3 = df['area'].quantile(0.75)
iqr = q3 - q1
upper_limit = q3 + 1.5 * iqr

print("\n Estadísticas de área:")
print(f" - Percentil 75 (Q3): {q3:.2f} m²")
print(f" - Límite superior para outliers (Q3 + 1.5*IQR): {upper_limit:.2f} m²")
print(f" - Máximo real observado: {df['area'].max():.2f} m²")

# Evaluar si el máximo es un outlier real o razonable
if df['area'].max() > upper_limit:
    print("\n El valor máximo supera el límite estadístico.")
    print("Sin embargo, considerando el contexto inmobiliario, puede representar propiedades grandes y no un error.")
else:
    print("\n El valor máximo está dentro del rango esperado.")

"""
- En bathrooms y bedrooms, se limitan los valores máximos a rangos habitacionales razonables. Dormitorios a 11 y baños a 8."""

max_bathrooms = (df['bathrooms'] > 8).sum()

print(f" Propiedades con más de 8 baños: {max_bathrooms}")

total = len(df)
porcentaje = (max_bathrooms / total) * 100
print(f" Propiedades con más de 8 baños:: {max_bathrooms} ({porcentaje:.2f}% del total)")

before_drop = len(df)
df = df[df['bathrooms'] <= 8]
after_drop = len(df)

max_bedrooms = (df['bedrooms'] > 11).sum()

print(f" Propiedades con más de 11 dormitorios: {max_bedrooms}")

total = len(df)
porcentaje = (max_bedrooms / total) * 100
print(f" Propiedades con más de 11 dormitorios: {max_bedrooms} ({porcentaje:.2f}% del total)")

before_drop = len(df)
df = df[df['bedrooms'] <= 11]
after_drop = len(df)

"""Cantidad de registros totales luego de las transformacionaes realizadas:"""

df.count()

plt.figure(figsize=(10, 6))
plt.scatter(df["area"], df["price"], alpha=0.3, edgecolor="k", s=20)
plt.title("Distribución del precio según la superficie")
plt.xlabel("Area (m²)")
plt.ylabel("Precio")
plt.xticks(rotation=45)
plt.locator_params(axis="x", nbins=10)

plt.show()

"""#### Conversión de tipos

"""

import re

def parse_coordinates(coord):
    if isinstance(coord, str):
        match = re.findall(r'-?\d+\.\d+', coord)
        if len(match) == 2:
            return float(match[0]), float(match[1])
    return (np.nan, np.nan)

print("Antes del parseo:")
print(df[['coordinates', 'latitude', 'longitude']].head(5))

#Parseo
df[['latitude', 'longitude']] = df['coordinates'].apply(
    lambda x: pd.Series(parse_coordinates(x))
)

# Verificar
print(" Conversión corregida desde 'coordinates':")
print(df[['latitude', 'longitude']].dtypes)
print("\nNulos después del parseo corregido:")
print(f" - latitude: {df['latitude'].isna().sum()}")
print(f" - longitude: {df['longitude'].isna().sum()}")

# Ver muestra
print("\n Ejemplo de coordenadas parseadas correctamente:")
print(df[['coordinates', 'latitude', 'longitude']].head(5))
df.drop(columns=['coordinates'], inplace=True)

"""#### Normalización de texto

"""

df['location'] = df['location'].str.lower().str.strip()
df['currency'] = df['currency'].str.upper().str.strip()
df['property_type'] = df['property_type'].str.lower().str.strip()

"""#### Generación de nuevas variables"""

import ast

# Convertir string de lista a lista real
df['labels'] = df['labels'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else [])

# Crear variables para los diferntes tipos de labels
df['is_destacado'] = df['labels'].apply(lambda x: 'DESTACADO' in x)
df['is_nuevo'] = df['labels'].apply(lambda x: 'NUEVO' in x)

df.drop(columns=['labels'], inplace=True)

df['property_type'].unique()

# --- Crear columnas binarias para tipos de propiedad clave ---
df['property_type'] = df['property_type'].str.lower().str.strip()

df['is_departamento'] = df['property_type'].apply(lambda x: 1 if 'departamento' in x else 0)
df['is_casa'] = df['property_type'].apply(lambda x: 1 if 'casa' in x else 0)

print("\nColumnas creadas correctamente:")
print(df[['is_departamento', 'is_casa']].head(5))

df.drop(columns=['property_type'], inplace=True)

"""#### Normalizacion y Estandariacion de los datos"""

from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler_minmax = MinMaxScaler()
scaler_std = StandardScaler()

# Crear copias escaladas
df_norm = df.copy()

col_norm = ['area']

df_norm[col_norm] = scaler_minmax.fit_transform(df_norm[col_norm])

df_norm.head()

""" ### ✍️ 6. Reflexión final

En este proceso de diagnóstico y transformación de los datos, se tomaron las siguientes decisiones:

- **Eliminación de columnas irrelevantes o con alta proporción de nulos:** Se identificaron y eliminaron columnas que no aportaban información útil para el análisis o modelado, como identificadores de scraping, URLs, y columnas con casi todos sus valores nulos (ej. `description`, `expenses`, `rooms`). Esto permitió reducir la dimensionalidad del dataset y enfocarse en variables más significativas.

- **Manejo de valores faltantes:** Para columnas clave como `area`, `bathrooms` y `bedrooms`, se optó por eliminar las filas con valores nulos, ya que representaban una parte menor del dataset y su imputación podría introducir sesgos. Para la moneda (`currency`), se imputaron los nulos con 'USD' al ser el valor más frecuente.

- **Tratamiento de Outliers:** Se realizó un análisis detallado de los outliers en variables numéricas (`price`, `area`, `bathrooms`, `bedrooms`). Se definieron umbrales basados en el contexto inmobiliario y en percentiles para filtrar valores extremos que parecían errores de carga o scraping, buscando mantener la consistencia de los datos sin eliminar información relevante sobre propiedades de alto valor o gran tamaño.

- **Conversión y normalización de tipos de datos:** Se transformaron columnas con formato inconsistente (ej. `coordinates`) a tipos numéricos (`latitude`, `longitude`) para facilitar su análisis. Se normalizó el texto en columnas categóricas (`location`, `currency`, `property_type`) para asegurar la uniformidad.

- **Creación de nuevas variables:** Se generaron variables binarias a partir de la columna `labels` (`is_destacado`, `is_nuevo`) y `property_type` (`is_departamento`, `is_casa`) para capturar características importantes de las propiedades de manera estructurada.

- **Normalización de variables numéricas:** Se aplicó MinMaxScaler a la columna `area` para normalizar su escala, preparándola para futuros modelos que puedan ser sensibles a la magnitud de las variables de entrada.

**Dificultades encontradas:**

La principal dificultad fue la gran cantidad de valores faltantes y la presencia de outliers significativos en variables clave como el precio y la superficie. Esto requirió un análisis cuidadoso para decidir cómo tratarlos sin perder información valiosa o introducir sesgos. La inconsistencia en el formato de las coordenadas también representó un desafío inicial.

**Siguientes pasos proyectados:**

1.  **Análisis más profundo de variables categóricas:** Explorar la distribución de las propiedades por `location` y otras variables categóricas restantes.
2.  **Creación de columnas adicionales:** Considerar la creación de nuevas variables, como el precio por metro cuadrado (`price_per_sqm`), o la distancia a puntos de interés a partir de las coordenadas.
3.  **Análisis de la variable objetivo (`price`):** Realizar una exploración más profunda de la distribución del precio después del tratamiento de outliers y considerar posibles transformaciones (ej. logarítmica) si la distribución es muy sesgada.
4. Análisis geoespacial de coordenadas (latitude, longitude): Realizar un estudio de patrones espaciales para identificar zonas preferenciales, áreas turísticas o de alto valor comercial, analizando cómo la ubicación geográfica influye en el precio y la demanda de propiedades.
5.  **Selección de características:** Evaluar la relevancia de las variables restantes para la predicción del precio.
6.  **Modelado:** Implementar un modelo de predicción del precio
7.  **Evaluación del modelo:** Medir el rendimiento del modelo utilizando métricas adecuadas.
"""